# Configuración de vagrant para tener un Adminserver y 3 nodos
Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 240
  servers=[
      {
        :hostname => "AdminServer",
        :box => "bento/ubuntu-18.04",
        :ip => "172.16.1.50",
        :ssh_port => '2200'
      },
      {
        :hostname => "node1",
        :box => "bento/ubuntu-18.04",
        :ip => "172.16.1.51",
        :ssh_port => '2201'
      },
      {
        :hostname => "node2",
        :box => "bento/ubuntu-18.04",
        :ip => "172.16.1.52",
        :ssh_port => '2202'
      },
      {
        :hostname => "node3",
        :box => "bento/ubuntu-18.04",
        :ip => "172.16.1.53",
        :ssh_port => '2203'
      }
    ]

  servers.each do |machine|
      config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]
          node.vm.network :private_network, ip: machine[:ip], netmask: "255.255.255.0", auto_config: false
          node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"
          node.vm.provider :virtualbox do |vb|
            if machine[:hostname] == "AdminServer"
              vb.customize ["modifyvm", :id, "--memory", 9216]
              vb.customize ["modifyvm", :id, "--cpus", 4]
              #vb.customize ["modifyvm", :id, "--diskcachestrategy", "Writethrough"]
              vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
              #vb.customize ["modifyvm", :id, "--mtu", "1400"]
              else
              vb.customize ["modifyvm", :id, "--memory", 1024]
              vb.customize ["modifyvm", :id, "--cpus", 1]
              #vb.customize ["modifyvm", :id, "--diskcachestrategy", "Writethrough"]
              vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
              #vb.customize ["modifyvm", :id, "--mtu", "1400"]
              end
          end
      end
  end
end
